### ISSUE TITLE
Python3.5 vs. Python 3.6

### ISSUE THREAD

**Issue by DdRanna** [tuhiproject/tuhi#100]
I know that TUHI requires Python v3.6 or above. However, the installation via 'python3 setup.py install' under ubuntu 16.04 does not work because e.g. svgwrite and apt_pkg are missing when I use 'search on' in kete.py.

What to do?

**Comment by whot** [comment]
I doubt 16.04 has python 3.6, it came out before the 3.6 release in november 2016. So your basic issue appears to be the 3.5 and 3.6 mixup that you have locally. I fixed this by adding dependencies to `setup.py` but beyond that there isn't much we can do in tuhi.

**Comment by DdRanna** [comment]
Yes, it seems to be a local mixup from my side. 
Still getting the error with python3.6 _ModuleNotFoundError: No module named 'apt_pkg'_ and _File "/usr/lib/python3/dist-packages/gi/overrides/Gio.py", line 171, in __call__  None)_
 when I start search via kete.

**Comment by whot** [comment]
that's pulled in by `gio` which is our dependency, but the error is inside gio. so what's missing here is a dependency for `gio` itself, but that's outside our control. do you have apt_pkg installed?
