### ISSUE TITLE
Bamboo Folio on Ubuntu 16.04

### ISSUE THREAD

**Issue by doctormo** [tuhiproject/tuhi#104]
This is Martin from the Inkscape Project. I have the Bamboo Folio, and have paired the device.

The first problem was that Tuhi won't work on Ubuntu 16.04 (at all) with python 3.6, I had to add compat for python 3.5. This is because gobject introspection modules aren't available for python3.6 on Ubuntu 16.04, even with PPA.

Once that was out the way, the tuhi program itself seemed to be doing things.

```
INFO: tuhi.ble: Connection established
INFO: tuhi.ble: Disconnected
```
Although the main program didn't do anything otherwise. There's a tuhi-live application, but it's very unhappy about being a) run as non-root and then b) being run as root and thus not having access to X11 DISPLAY. Which means it can't work. Not sure how to fix that.

**Comment by doctormo** [comment]
Running the start search method via DFeet provides a core dump (awesome):

```
/home/doctormo/Projects/tuhi/tuhi/dbusserver.py:131: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
  builder = GLib.VariantBuilder(GLib.VariantType('a{sv}'))
/home/doctormo/Projects/tuhi/tuhi/dbusserver.py:135: Warning: g_variant_builder_add_value: assertion 'is_valid_builder (builder)' failed
  builder.add_value(de)
/home/doctormo/Projects/tuhi/tuhi/dbusserver.py:136: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
  properties = builder.end()
/home/doctormo/Projects/tuhi/tuhi/dbusserver.py:137: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
  inval_props = GLib.VariantBuilder(GLib.VariantType('as'))
/home/doctormo/Projects/tuhi/tuhi/dbusserver.py:138: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
  inval_props = inval_props.end()
/usr/lib/python3/dist-packages/gi/overrides/GLib.py:250: Warning: g_variant_ref_sink: assertion 'value != NULL' failed
  return GLib.Variant.new_tuple(elements)
Segmentation fault (core dumped)
```

**Comment by whot** [comment]
>  b) being run as root and thus not having access to X11 DISPLAY. Which means it can't work. Not sure how to fix that.
```
$ xhost si:localuser:root
$ sudo DISPLAY=:0 whatever-program-to-run
```
That should do the trick. In some cases the `DISPLAY` is some other number, just run `echo $DISPLAY` on the terminal to make sure.


but, tbh, the crash looks like #103 and is some result of the old python version on ubuntu. The crash you're getting here is inside `gi`. It works here, so right now I'm strongly inclined to blame the PPA, especially since you say you had to add compat for 3.5. So short story: without python 3.6 you're bound to just make life hard for yourself :)

**Comment by doctormo** [comment]
I figured that would be your answer. Although I'm very reluctant to install a testing version of Ubuntu to get access to a hardware driver, this is a really important thing to have backwards compatibility to the current LTS and an LTS that's going to be around for a while.

If I work on the problem, can the project support changes to support python 3.5?

**Comment by whot** [comment]
I think the only real need for 3.6 that we have are the `f`-strings that only came with 3.6. Without that, printing is ugly. Compare:
```print(f'{device.address}: something happened on {device.name}: {value}')```
to
```print('{}: something happened on {}: {}'.format(device.address, device.name, value))``` 

Unfortunately, `f`-strings cannot be backported to 3.5 and there is no good middle-ground. I always hated the `.format` syntax, using `f` made life a lot easier. We were also under the assumption that  a python version released in 2016 is sufficiently old to be supported, especially for a new project (#29). 

Either way, it still comes down to: it's a messy patch to change everything, @bentiss and I don't have 3.5 so we wouldn't notice if we accidentally break it. It makes life easier for the developers and python 3.6. is available in Ubuntus 17.04, 17.10 and 18.04 (let's pretend I see into the future). I don't think 17.04 and 17.10 count as a 'testing version' anymore, and iirc 18.04 will be an LTS. So yeah, I'd much rather you update to something less than 2 years old than us having to try to add backwards-compat for something that old. Who knows what else will break once the format strings have been changed.

Sorry, can't make everyone happy here but there's a reasonably high chance you'll update to 18.04 in a few months anyway, right? So a backport wouldn't really be worth it, IMO.

**Comment by doctormo** [comment]
I'll keep the kit on the shelf and come back next year to it.

**Comment by bentiss** [comment]
One thing I'd recommend in this case, is to use the flatpak solution.
Install `flatpak` and `flatpak-builder` (https://flatpak.org/getting.html), and then:

- to be done once (it will download ~200MB of data):
```bash
$> flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
$> flatpak install flathub org.freedesktop.Platform org.freedesktop.Sdk
```

- to create the flatpak:
```bash
$> flatpak-builder --force-clean flatpak-tuhi org.freedesktop.tuhi.json
```
- to locally run the app:
```bash
$> flatpak-builder --run flatpak-tuhi org.freedesktop.tuhi.json tuhi-kete -v
```
or
```
$> flatpak-builder --run flatpak-tuhi org.freedesktop.tuhi.json tuhi -v
```
if you just want to check something on the DBus API.

Just repeat the `flatpak-builder` steps every time you change something in the python sources.
The creation of the flatpak will speed up once it has been done once, so do not be afraid by the initial long compilation time.

Of course, if someone wants to create a snap (snappy?) for a better integration with Ubuntu, we would be glad to take any PR.
