### ISSUE TITLE
How to access drawing data

### ISSUE THREAD

**Issue by hannahwolfe** [tuhiproject/tuhi#108]
I have managed to connect to the bamboo spark tablet using bluetoothctl.  Once I am connected what is the process to receive data?

Thank you.

**Comment by whot** [comment]
The `fetch` command downloads the drawing from the host, you have to specify
the timestamp. Also try the `help` command on the kete shell, it lists the
commands available to you.

**Comment by hannahwolfe** [comment]
I am sorry, maybe I am going through the process incorrectly.
1.  Start tuhi shell (nothing happens)
2.  Start "bluetoothctl"
    2a. "scan on"
    2b. "connect device_id"  (tuhi shell says "INFO: tuhi.ble: Connection established" )
3.  unknown next step....

I have also tried to use kete, after starting tuhi.  Under tools I can type "python3 kete.py" and it says 
"Tuhi shell control
INFO: Connected to the Tuhi daemon
tuhi> "
When I type "search on" the kete shell crashes because Tuhi crashes.
"/usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:131: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
/usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:135: Warning: g_variant_builder_add_value: assertion 'is_valid_builder (builder)' failed
/usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:136: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
/usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:137: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
/usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:138: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
/usr/lib/python3/dist-packages/gi/overrides/GLib.py:250: Warning: g_variant_ref_sink: assertion 'value != NULL' failed
  return GLib.Variant.new_tuple(elements)
Segmentation fault
"

**Comment by whot** [comment]
> I am sorry, maybe I am going through the process incorrectly.
> 1.  Start tuhi shell (nothing happens)
> 2.  Start "bluetoothctl"
>     2a. "scan on"
>     2b. "connect device_id"  (tuhi shell says "INFO: tuhi.ble: Connection established" )
> 3.  unknown next step....

you shouldn't need these, aside from switching bluetooth on. Start `tuhi
--verbose` and leave it running. Once running, start `kete` and type `search
on`. Now you can press and hold the blue button to register. Once the device
shows up (check the kete output), you can do `register <MAC>`.

> 
> I have also tried to use kete, after starting tuhi.  Under tools I can type "python3 kete.py" and it says 
> "Tuhi shell control
> INFO: Connected to the Tuhi daemon
> tuhi> "
> When I type "search on" the kete shell crashes because Tuhi crashes.
> "/usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:131: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
> /usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:135: Warning: g_variant_builder_add_value: assertion 'is_valid_builder (builder)' failed
> /usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:136: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
> /usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:137: TypeError: Passing arguments to gi.types.Boxed.__init__() is deprecated. All arguments passed will be ignored.
> /usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:138: Warning: g_variant_builder_end: assertion 'is_valid_builder (builder)' failed
> /usr/lib/python3/dist-packages/gi/overrides/GLib.py:250: Warning: g_variant_ref_sink: assertion 'value != NULL' failed
>   return GLib.Variant.new_tuple(elements)
> Segmentation fault
> "

sigh, I'm beginning to think using python was a bad idea. This is something
somewhere within GI and python. What distribution are you on and does it
have python 3.6 natively or did you have to manage that yourself?

**Comment by hannahwolfe** [comment]
I'm on ubuntu 16.04, with python 3.6 installed from a ppa.

**Comment by whot** [comment]
right, that's most likely the issue then, the gobject introspection bits are tied to the python version, so if you use old gi for 3.5 with python 3.6 from a ppa, things blow up. Sorry, not something we can fix in tuhi.

**Comment by hannahwolfe** [comment]
If this is an issue about 3.6 python in ubuntu 16.04, it would be helpful to have it on the readme with the python 3.6 requirement.

**Comment by whot** [comment]
We do, see the "TUHI requires Python v3.6 or above." blurb. We also check for for python 3.6 in `main()` but this gi issue circumvents it.

**Comment by pbhogale** [comment]
Same issue. @hannahwolfe how did you fix this eventually ?

In my case, I have python 3.6 provided by Anaconda. 
```
/home/uname/anaconda3/lib/python3.6/site-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:135: Warning: g_variant_builder_add_value: assertion 'ensure_valid_builder (builder)' failed
/home/uname/anaconda3/lib/python3.6/site-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:136: Warning: g_variant_builder_end: assertion 'ensure_valid_builder (builder)' failed
/home/uname/anaconda3/lib/python3.6/site-packages/tuhi-0.1-py3.6.egg/tuhi/dbusserver.py:138: Warning: g_variant_builder_end: assertion 'ensure_valid_builder (builder)' failed
/home/uname/anaconda3/lib/python3.6/site-packages/PyGObject-3.29.2.dev0-py3.6-linux-x86_64.egg/gi/overrides/GLib.py:178: Warning: g_variant_ref_sink: assertion 'value != NULL' failed
  return GLib.Variant.new_tuple(elements)
Segmentation fault
```

**Comment by whot** [comment]
I'm gonna have to close this one as wontfix. AFAICT the issue here is with the python 3.6 installs, not with tuhi itself so nothing we can fix here.
