### ISSUE TITLE
Add per client "grabbing" mechanism

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#11]
### Use case:
_you have 2 devices. Device 1 is use to take quick and random notes. Device 2 is used to keep super important notes._

### Expected client usage:
- Device 1 can be synched no matter what, by any app (one time it'll be inkscape, the other time it'll be the email client to share a drawing)
- Device 2 should only be synched by a specific app **SuperImportantApp** that will keep all the notes of this device.

### Consequences:
- Device 1 can be set to the `listen` mode by anybody
- Device 2 should only be synched by **SuperImportantApp**. The config file should retain this information and the daemon should only allow the matching app to call the sync method.

**Comment by whot** [comment]
If we have some permanent storage on the daemon (see #3) then it's more an issue of who is allowed to get the files than who can listen to the device. Given that in all cases it's going to be us who actually syncs the device anyway. Not sure how dbus works for remote end-point verification. I found a bit for auth stuff, but that's not enough to form an opinion.

**Comment by whot** [comment]
Closing this, no usecase in 18 months and with the gui now the server-only usecase itself has become more niche, let alone the idea of having multiple devices and separate clients.
