### ISSUE TITLE
Broken stroke data with Bamboo Slate offline mode

### ISSUE THREAD

**Issue by espresso3389** [tuhiproject/tuhi#111]
In certain cases, offline strokes may start with relative Y coordinate.
Current code in [get_coordinate](https://github.com/tuhiproject/tuhi/blob/master/tuhi/wacom.py#L732) assumes the first point is absolute or otherwise the point is ignored.

I found that, in certain cases, Y and Z of the first point might be relative and then we should use the byte sequence of [WacomPacketHandlerStrokePrefixSlate](https://github.com/tuhiproject/tuhi/blob/master/tuhi/wacom.py#L253) as if it were a previous coordinate triplet.

That is, `WacomPacketHandlerStrokePrefixSlate` seems always starts with `?f,ff,ee,ee,ee` but last padded 4 bytes can be interpreted as Y0 and Z0. And the first point should be calculated against the Y0 and Z0 if the first point has relatively coded values.

**Comment by whot** [comment]
thx! just ftr, we're really struggling for time on tuhi atm, it's been untouched for a few months now - any help would be appreciated.

**Comment by whot** [comment]
fwiw, any data log would be useful here, in case someone comes around a year or so later and wants to fix this ;)

**Comment by whot** [comment]
I managed to trigger this on a Spark which doesn't have a stroke prefix at all. First bytes in the recording are

```0x62, 0x38, 0x62, 0x74, 0xbf, 0xff, 0xff, 0x4a, 0x14, 0x29, 0x31, 0x6a```

The first four are the file format, `bf` is the first bitmask. `ff ff` is the stroke handler and then we have 2 bytes for x, two for y and 1 for pressure. So I guess defaulting to 0, 0, 0 for the first point is the sensible option here.
