### ISSUE TITLE
What is the state of this project?

### ISSUE THREAD

**Issue by falematte** [tuhiproject/tuhi#112]
Thank you for the great work! I would like to ask if someone is currently downloading drawings and convert them to pdf on linux machines.

**Comment by bentiss** [comment]
Downloading drawings should be working already. It will download them as svg, so then it should be pretty strightforward to convert the drawings into PDF.

However, I think there are a few issues (#109 #111), but we are really lacking time to work on this. We would welcome any contributions.

**Comment by aicherm** [comment]
Thank you for your awesome work! I really like this project!
Could you provide a section with ToDo's to the Readme or define some kind of work packages that have to be done? I think this could help to find a starting point for contributions.

**Comment by whot** [comment]
fwiw, one of the big ticket items right now is developing a GUI for Tuhi, so the commandline option isn't the only thing we have available.

In regards to the original question of converting them to PDF - I think that's out of scope for Tuhi, we should leave that to tools that specialise in svg->pdf conversion. Especially given that we may have some issues with the SVG data that would need to be fixed anyway (#109).

There are no specific work packages, but I'd consider #111 and #109 to be the highest on the TODO list right now.

**Comment by whot** [comment]
Closing this after merging the GUI into the main repository (#145 )
