### ISSUE TITLE
Beginner documentation needed

### ISSUE THREAD

**Issue by whot** [tuhiproject/tuhi#114]
After many moons of not looking at Tuhi, I already forgot how everything works and, most notably, what to do. We really need some docs here.

**Comment by bentiss** [comment]
IIRC, the gist of it is:
- start `tuhi.py` (as normal user)
- launch `kete.py` (as normal user too)
- in `kete`, run `help` and go from there :)

There is also the live mode that you can start with `sudo ./tools/tuhi-live.py` (it needs root to have acccess to the `uhid` node).

**Comment by gbraad** [comment]
This should be part of the `README`?

**Comment by whot** [comment]
I've started adding bits to the wiki and will add more (well, rewrite) once #145 is done. Closing this for now, because there's no point in keeping this open right now.
