### ISSUE TITLE
Empty list of drawings strange dimension

### ISSUE THREAD

**Issue by lukyluket** [tuhiproject/tuhi#115]
Hallo, I finally managed to connect to my bamboo (had to buy a usb bluetooth dongle).
I have now a couple of issues, first on connecting I get this message

uhi> INFO: tuhi.wacom: device name is b'Bamboo luca\n'
ERROR: tuhi.wacom: incompatible dimensions: 29700x21600
INFO: tuhi.wacom: firmware is B160805A-C160909B
INFO: tuhi.wacom: registration completed
INFO: tuhi.ble: FB:ED:B6:C3:52:9B: Disconnecting

However when I then press info it still looks like I am connected though the battery info is absent and the list of drawings is also absent 
info gives:
FB:ED:B6:C3:52:9B - Bamboo luca
        Battery level: 0%, unknown
        Available drawings:

Are the two issues related?

Finally in live mode, it looks that the size of my slate is supposed to be A5 since with only a small part of the page I can cover the full scree, from xinput -list-props I see the following output 

        Wacom Tablet Area (281):        2500, 500, 20600, 14300
That I guess is the line that sets the size, should I try to change this to enlarge the area on the paper I can use in order to address the full screen?

Kind regards
Luca

**Comment by whot** [comment]
Can you please attach a log file of a connection attempt from `tuhi --verbose` please? Without that we probably won't know what's going on.

**Comment by whot** [comment]
>  the battery info is absent 

This was fixed with 05fd2139400514a80f39c7fc303234b7fb1e6e2c

**Comment by lukyluket** [comment]
I am currently traveling will send it as soon as possible
Thanks
Luca

**Comment by whot** [comment]
FTR, we have access to the specs under NDA now, and the stroke data is relatively complex. so it's quite likely that this is just a bug. Not sure if the stroke data differs between the versions though, we only have partial specs.

**Comment by whot** [comment]
Let's close this, it's been almost 3 years - please re-open if it's still an issue
