### ISSUE TITLE
Bamboo Slate Small fails to synching due to unexpected opcode

### ISSUE THREAD

**Issue by gbraad** [tuhiproject/tuhi#117]
This happens right after registering the device:

```
gi.repository.GLib.Error: g-io-error-quark: An object is already exported for the interface org.freedesktop.tuhi1.Device at /org/freedesktop/tuhi1/DC_5E_A8_FA_09_9D (2)
INFO: tuhi.ble: Connection established
INFO: tuhi.ble: Connection established
INFO: tuhi.wacom: Press the button now to confirm
INFO: DC:5E:A8:FA:09:9D - Bamboo Slate Small: Press button on device now
tuhi> register DC:5E:A8:FA:09:9D
INFO: tuhi.ble: DC:5E:A8:FA:09:9D: Device is already connected
ERROR: tuhi.wacom: DC:5E:A8:FA:09:9D: already synching, ignoring this request
tuhi> INFO: tuhi.wacom: device name is b'Bamboo Slate Small'
ERROR: tuhi.wacom: **** Exception: unexpected opcode: bc ****
INFO: tuhi.ble: DC:5E:A8:FA:09:9D: Disconnecting
INFO: tuhi: unexpected opcode: bc
INFO: tuhi.dbus: An error occured while synching the device
INFO: tuhi.ble: Disconnected
INFO: tuhi.ble: Disconnected
```

**Comment by gbraad** [comment]
@whot you think this might be related to the device or firmware? I haven't tried the A4 (large) size, but to compare I will.

**Comment by whot** [comment]
Who knows... we reverse-engineered the protocol and we only had access to two devices. The slate small wasn't one of those so if anything changed there it's likely we need to special-case this. The output from `tuhi --verbose` is likely to be useful, iirc this includes the full protocol dump.

**Comment by gbraad** [comment]
I have tried on the larger version and it suceeds:

```
INFO: Unregistered device: F3:82:22:51:39:36 - Bamboo Slate
tuhi> register F3:82:22:51:39:36
INFO: tuhi.ble: F3:82:22:51:39:36: Connecting
tuhi> INFO: tuhi.ble: Connection established
INFO: tuhi.wacom: Press the button now to confirm
INFO: F3:82:22:51:39:36 - Bamboo Slate: Press button on device now
tuhi> INFO: tuhi.wacom: device name is b'Bamboo Slate\n'
ERROR: tuhi.wacom: incompatible dimensions: 29700x21600
INFO: tuhi.wacom: firmware is B160805A-C170704A
INFO: tuhi.wacom: registration completed
INFO: tuhi.ble: F3:82:22:51:39:36: Disconnecting
INFO: F3:82:22:51:39:36 - Bamboo Slate: Registration successful
tuhi> INFO: tuhi.ble: Disconnected
```

I will look into this...

**Comment by gbraad** [comment]
While running as `thui --verbose` the response from `kete` is different and seems to succeed?

```
INFO: tuhi.ble: DC:5E:A8:FA:09:9D: Connecting
DEBUG: tuhi: /org/bluez/hci0/dev_DC_5E_A8_FA_09_9D: call Register() on device
INFO: tuhi.ble: Connection established
DEBUG: tuhi: DC:5E:A8:FA:09:9D: connected for DeviceMode.REGISTER
DEBUG: tuhi.wacom: DC:5E:A8:FA:09:9D: starting
DEBUG: tuhi.wacom: DC:5E:A8:FA:09:9D: registering device, assigned 89ea7888ffcb
DEBUG: tuhi.fw: TX Nordic --> e7 / 06 / 89 ea 78 88 ff cb
INFO: tuhi.wacom: Press the button now to confirm
DEBUG: tuhi.dbus: Sending ButtonPressRequired signal
DEBUG: tuhi.fw: RX Nordic <-- e4 01 00
DEBUG: tuhi.wacom: received e4 / 01 / 00
DEBUG: tuhi.wacom: Bamboo Slate Small is using protocol Protocol.SLATE
DEBUG: tuhi.fw: TX Nordic --> b6 / 06 / 19 03 15 03 22 16
DEBUG: tuhi.fw: RX Nordic <-- b3 01 00
DEBUG: tuhi.wacom: received b3 / 01 / 00
DEBUG: tuhi.fw: TX Nordic --> b6 / 01 / 00
DEBUG: tuhi.fw: RX Nordic <-- bd 06 19 03 15 03 22 16
DEBUG: tuhi.wacom: received bd / 06 / 19 03 15 03 22 16
DEBUG: tuhi.wacom: b6 returned time: UTC 190315032216
DEBUG: tuhi.fw: TX Nordic --> ec / 06 / 06 00 00 00 00 00
DEBUG: tuhi.fw: RX Nordic <-- b3 01 00
DEBUG: tuhi.wacom: received b3 / 01 / 00
DEBUG: tuhi.fw: TX Nordic --> bb / 01 / 00
DEBUG: tuhi.fw: RX Nordic <-- bc 12 42 61 6d 62 6f 6f 20 53 6c 61 74 65 20 53 6d 61 6c 6c
DEBUG: tuhi.wacom: received bc / 12 / 42 61 6d 62 6f 6f 20 53 6c 61 74 65 20 53 6d 61 6c 6c
INFO: tuhi.wacom: device name is b'Bamboo Slate Small'
DEBUG: tuhi.fw: TX Nordic --> ea / 02 / 03 00
DEBUG: tuhi.fw: RX Nordic <-- bc 09 00 42 61 6d 62 6f 6f 20 0a
DEBUG: tuhi.wacom: received bc / 09 / 00 42 61 6d 62 6f 6f 20 0a
ERROR: tuhi.wacom: **** Exception: unexpected opcode: bc ****
INFO: tuhi.ble: DC:5E:A8:FA:09:9D: Disconnecting
INFO: tuhi: unexpected opcode: bc
INFO: tuhi.dbus: An error occured while synching the device
DEBUG: tuhi.fw: RX Nordic <-- eb 06 03 00 60 54 00 00
INFO: tuhi.ble: Disconnected
DEBUG: tuhi: DC:5E:A8:FA:09:9D: disconnected
```

```
INFO: Search started
INFO: Unregistered device: DC:5E:A8:FA:09:9D - Bamboo Slate Small
tuhi> register DC:5E:A8:FA:09:9D
INFO: DC:5E:A8:FA:09:9D - Bamboo Slate Small: Press button on device now
tuhi> 
```

seems the verbose mode consumes the error and does not return it anymore to the REPL tool.

**Comment by whot** [comment]
> DEBUG: tuhi.fw: TX Nordic --> bb / 01 / 00
> DEBUG: tuhi.fw: RX Nordic <-- bc 12 42 61 6d 62 6f 6f 20 53 6c 61 74 65 20 53 6d 61 6c 6c

That's the "get name" request and it replies with "Bamboo Slate Small'

> DEBUG: tuhi.fw: TX Nordic --> ea / 02 / 03 00

That's the "get dimensions" request but we get 

> DEBUG: tuhi.fw: RX Nordic <-- bc 09 00 42 61 6d 62 6f 6f 20 0a

which is another "get name" reply, reading as "Bamboo \n". But we expect the "get dimensions" reply 0xeb. And we do get that, later:

> DEBUG: tuhi.fw: RX Nordic <-- eb 06 03 00 60 54 00 00

So it looks like this tablet replies with two packets to the "get name reply", for whatever reason. But we only expect one. We could work around this by just testing if we get another packet and discarding it.

Open up `tuhi/wacom.py` and in `get_name()`, change it to something like this:

```python
def get_name(self):
    data = self.send_nordic_command_sync(command=0xdb, expected_opcode=0xbc)
    try:
         self.wait_nordic_data(expected_opcode=[0xbc], timeout=0.2)
    except WacomTimeoutException:
       pass
    return bytes(data)
```

So that `try/except` block is new, it tries to read some more data from the device and we discard it. If we time out, we ignore the timeout error too. So this may paper over the error you're seeing.

**Comment by gbraad** [comment]
Will try this later. I also notice that the name of the device is reported in the Microsoft Store version of Inkspace as "Bamboo Slate Small□", like the usual unicode response when there is an unrecognized character. Although, on Android this is not shown.

**Comment by lukyluket** [comment]
I am not sure if the problem is the same, but my slate (the A4) does not sync either, it connects and then disconnects saying unexpected size, is it related?
Please see the other issue 
https://github.com/tuhiproject/tuhi/issues/115

**Comment by gbraad** [comment]
I reset the device (paperclip for three to five second from the pinhole next to the USB charge socket). It took a few times to register (failing to do so) due to it having a registered bluetooth device. This would cause:

```
DEBUG: tuhi: /org/bluez/hci0/dev_DC_5E_A8_FA_09_9D: call Register() on device
INFO: tuhi.ble: DC:5E:A8:FA:09:9D: Connecting
DEBUG: tuhi: /org/bluez/hci0/dev_DC_5E_A8_FA_09_9D: call Register() on device
INFO: tuhi.ble: Connection established
INFO: tuhi.ble: Disconnected
DEBUG: tuhi: DC:5E:A8:FA:09:9D: disconnected
```

which shows it connects and immediately disconnects. I removed the registration from the Gnome control center and reset the device again... and this eventually passed the `tuhi &; ./kete.py` device register.

**Comment by gbraad** [comment]
Closing the issue for now, as it looked the device had an issue with the device name or some other state, which caused it not to communicate correctly.

I do think the communication might be made a little bit more resilient

**Comment by whot** [comment]
> I do think the communication might be made a little bit more resilient

suggestions welcome, but since this is all reverse-engineered it's hard to know what to do when we send request 1234 but don't get the expected reply 5678. Do we re-try (potentially making things worse). Do we ignore it, and thus lack information required to get info from the device?
