### ISSUE TITLE
Live mode: define custom region to which pen coordinates map

### ISSUE THREAD

**Issue by jose1711** [tuhiproject/tuhi#125]
I have 3 monitors side-by-side and a Bamboo Slate A4 tablet. When I run `kete-live.py` the A4 area of tablet (297x210) is mapped to the virtual screen of X11 (4640x1080). That results in any drawing to be horizontally stretched as the aspect ratio differs significantly (1.414 vs 4.30). It would be nice if I could define a region on any of the monitor to which the pen moves would translate to (Krita canvas for instance).

**Comment by whot** [comment]
I think that's more of a display server job. tuhi-live creates a virtual tablet device that  what looks essentially like a  tablet, so similar to say a Wacom Cintiq. The mapping to screen coordinates is then done by the display server (Xorg or the Wayland Compositor), that's where any mapping limits should be too.

I guess for this to work automatically we'd have to add a libwacom entry (you can do a local one) that identifies the tablet correctly so GNOME maps it to a screen. Other DEs - not so much :) But you can look up the Xorg "Coordinate Transformation Matrix" to map the coordinates to a part of the screen, google has plenty of results there.

**Comment by jose1711** [comment]
Thank you. Shortly after filing the issue I found this article: https://github.com/linuxwacom/xf86-input-wacom/wiki/Dual-and-Multi-Monitor-Set-Up. Did the calculation for my setup:
```
left:   1920x1080
center: 1280x1024
right:  1440x900	

combined: 4640 x 1080

  left                       center                             right
[ 1920/4640         0 0 ]  [ 1280/4640         0 1920/4640 ]  [ 1440/4640       0  3200/4640 ]
[         0 1080/1080 0 ]  [         0 1024/1080         0 ]  [         0 900/1080         0 ]
[         0         0 1 ]  [         0         0         1 ]  [         0        0         1 ]

  left             center                     right
[ 0.4138  0 0 ]  [ 0.2759      0  0.4138 ]  [ 0.3103       0  0.6897 ]
[      0  1 0 ]  [      0 0.9481       0 ]  [      0  0.8333       0 ]
[      0  0 1 ]  [      0      0       1 ]  [      0       0       1 ]
```
and made a test with the left monitor:
```
xinput set-prop "Wacom Bamboo Slate Pen Pen (0)" "Coordinate Transformation Matrix" 0.4138 0 0 0 1 0 0 0 1
```
It worked but it would be great if `tuhi` or maybe another tool made these calculations for me and provided some hints.

**Comment by whot** [comment]
xinput has `map-to-output` which is about as close as you can get here. Not something I'm planning to add to tuhi though, it's a bit out of scope.
