### ISSUE TITLE
Command 0xb1 == SET_MODE?

### ISSUE THREAD

**Issue by bartsch** [tuhiproject/tuhi#134]
I'm moving request and reply ids into enums in a distinct file nordi.py atm, like this:
```
class RequestID(enum.Enum):
    ...
    GET_BATTERY_INFO = 0xb9
    ...
```

There's command id 0xb1, which is used with different arguments in start_live(), stop_live() and read_offline_data(). Sounds to me like `SET_MODE = 0xb1`.
Right or at least acked?

**Comment by whot** [comment]
I don't think we need a separate `nordic.py` file here, this can just go into `wacom.py`. But otherwise, sure, sounds good.

**Comment by bartsch** [comment]
> I don't think we need a separate `nordic.py` file here, this can just go into `wacom.py`. But otherwise, sure, sounds good.

Just went on with testing and it looks like I'm forced to use a distinct file, even replace enums. Because, I want to hook up the id information in `parse_log` for more detailed dumps. Though, the `btsnoop` module requires Python 2.7, which clashes with a lot in `wacom.py` and enums are unavailable.

**Comment by whot** [comment]
the first result for [btsnoop on pypi](https://pypi.org/project/btsnoop/) says 3.7. just in case you hadn't found that one already, i spent all of 30s searching :)

**Comment by bartsch** [comment]
Though, that's not the `btsnoop` used in `parse_log`. ;-) This one: [python-btsnoop](https://github.com/joekickass/python-btsnoop)

**Comment by bartsch** [comment]
Closing, because my initial question (0xb1 == SET_MODE?) has been answered.

And for the second part (parse_log vs. Python 3+ imports), I have found a Python3-aware fork of the btsnoop module: [traviswpeters/btsnoop](https://github.com/traviswpeters/btsnoop)
