### ISSUE TITLE
Pressure data maximum

### ISSUE THREAD

**Issue by muesli** [tuhiproject/tuhi#142]
The README claims:

```
Stylus pressure is normalized to a range of [0, 0xffff], inclusive.
```

However looking at the raw JSON data it seems 2047 (0x7ff respectively) is the maximum value we extract.

**Comment by whot** [comment]
Looks like the Intuos Pro can do 4096 pressure levels, but really what is missing here is that we don't actually normalize the device data into the announced range. Should be done in `parse_pen_data()` from a quick peek at the source.
