### ISSUE TITLE
Recovery instructions and / or recovery tool

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#179]
There is currently a `test-svg.py` tool that can actually recover from previous sessions the data based on the raw events we caught during those session.

This is very useful but:

- [x] we need to document this somewhere (wiki, `readme.md`) that if a drawing is not pulled properly with version `x`, upgrading to version `y` where the bug is fixed allows to recover the missed drawings
- [x] we need to document how to fully recover a log
- [x] the tool needs to provide json data that are compatible with the current tuhi. For example, when copying the json output in my `$HOME/.local/share/tuhi/` folder, I have the following error:
```shell
09:28:53 INFO: tuhi.gui.dbus: manager is online
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/gi/_propertyhelper.py", line 404, in obj_set_property
    prop.fset(self, value)
  File "/home/btissoir/Src/tuhi/tuhi/gui/drawingperspective.py", line 142, in device
    self._update_drawings(Config.instance(), None)
  File "/home/btissoir/Src/tuhi/tuhi/gui/drawingperspective.py", line 89, in _update_drawings
    for js in sorted(config.drawings, reverse=True, key=lambda j: j['timestamp']):
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by whot** [comment]
https://github.com/tuhiproject/tuhi/wiki/Recovering-Drawings

**Comment by bentiss** [comment]
I guess we can close this now
