### ISSUE TITLE
tuhi-kete is too close to the DBus API (provide a bash like CLI)

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#18]
In a sense it's nice for developers, but terrible for users.

The user needs to run list, then listen, draw something, one device is there, but there is no trace of where it went, so Ctrl-C, fetch. But then you have to listen again, etc...

It's a good match for the DBus API, but honestly I am not sure anybody sane will understand this unless they know the internal and the architecture of the whole project.

 We should probably provide a bash like CLI in the same way bluetoothctl does.
We could notify users, and keep the states in the CLI.

Not sure whether this needs to be assigned a new subproject or not (probably not in the first place)

**Comment by whot** [comment]
Fixed with the series up to 7d86305b5242cf
