### ISSUE TITLE
move tuhi-kete out of the root folder

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#19]
tuhi-kete is a fun name, but not very descriptive unless you are native from Australia.
It should not be in the root of the project, as it's just a debugging tool for now.

How about we create a new folder (`tools`) and store it there?

**Comment by whot** [comment]
just for the record, kete is Maori and I don't speak maori (and australians in general don't, unless they have some kiwi heritage). You'd be hard-pushed to find people without that heritage to know more Maori than Kia Ora :)
