### ISSUE TITLE
Kete: add a `--listen` option to the `fetch` command

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#20]
Maybe, we should add a `--listen` option to the `fetch` command.

This would make the tuhi-kete a whole lot easier to run:
`tuhi-kete.py fetch --all --listen --to-svg` and svg would populate `$PWD` as they come in.

Drawback would be that people will stick to that and we won't be able to change the API anymore :(

**Comment by bentiss** [comment]
answer is Nahh...

**Comment by whot** [comment]
See #18 for a better solution
