### ISSUE TITLE
DeviceError.AUTHORIZATION_ERROR

### ISSUE THREAD

**Issue by aicherm** [tuhiproject/tuhi#212]
Hey,
I have trouble connecting my Slate with the current build of tuhi.
The device is registered within bluez but when pressing the Slates button I get:

> DEBUG: tuhi: D1:DA:E1:73:86:1F: UUID a0bd39117974 protocol: slate
> DEBUG: tuhi.ble.D1:DA:E1:73:86:1F: Connecting
> DEBUG: tuhi.ble.D1:DA:E1:73:86:1F: Connection established
> DEBUG: tuhi.fw: D1:DA:E1:73:86:1F: RX SYSEVENT <-- b'f1021300'
> DEBUG: tuhi.fw: sessionid: b2eda55b019e41c4bd81d315a66fb97d-3
> DEBUG: tuhi.fw: D1:DA:E1:73:86:1F: RX SYSEVENT <-- b'f1021300'
> DEBUG: tuhi: D1:DA:E1:73:86:1F: connected for DeviceMode.LISTEN
> DEBUG: tuhi.wacom: D1:DA:E1:73:86:1F: starting for mode LISTEN
> DEBUG: tuhi.fw: command: CONNECT
> DEBUG: tuhi.fw: D1:DA:E1:73:86:1F: TX NORDIC --> e6 / 06 / a0 bd 39 11 79 74
> DEBUG: tuhi.fw: D1:DA:E1:73:86:1F: RX NORDIC <-- b3 01 07
> ERROR: tuhi.wacom: **** Exception: DeviceError.AUTHORIZATION_ERROR ****
> DEBUG: tuhi.ble.D1:DA:E1:73:86:1F: Disconnecting
> INFO: tuhi: DeviceError.AUTHORIZATION_ERROR
> INFO: tuhi.dbus: An error occured while synching the device
> DEBUG: tuhi.dbus: Listening stopped on Bamboo Slate for :1.281
> ERROR: tuhi.dbusclient: D1:DA:E1:73:86:1F - Bamboo Slate: an error occured: Protocol error
> INFO: tuhi.gui.window: Device error: -71
> DEBUG: tuhi.dbus: Listening started on Bamboo Slate for :1.281
> DEBUG: tuhi.ble: /org/bluez/hci0: Discovery stopped
> DEBUG: tuhi.ble: /org/bluez/hci0: Discovery started (timeout 0)
> DEBUG: tuhi.ble.D1:DA:E1:73:86:1F: Disconnected
> DEBUG: tuhi: D1:DA:E1:73:86:1F: disconnected

I'm not so much into BLE so I cannot trace this error deeper.
Here is the output of gatttool showing the available UUIDs:

>[D1:DA:E1:73:86:1F][LE]> primary
>attr handle: 0x0001, end grp handle: 0x0007 uuid: 00001800-0000-1000-8000-00805f9b34fb
>attr handle: 0x0008, end grp handle: 0x000b uuid: 00001801-0000-1000-8000-00805f9b34fb
>attr handle: 0x000c, end grp handle: 0x0012 uuid: 00001523-1212-efde-1523-785feabcd123
>attr handle: 0x0013, end grp handle: 0x001b uuid: ffee0001-bbaa-9988-7766-554433221100
>attr handle: 0x001c, end grp handle: 0x001f uuid: 0000180f-0000-1000-8000-00805f9b34fb
>attr handle: 0x0020, end grp handle: 0x002c uuid: 0000180a-0000-1000-8000-00805f9b34fb
>attr handle: 0x002d, end grp handle: 0x0032 uuid: 6e400001-b5a3-f393-e0a9-e50e24dcca9e
>attr handle: 0x0033, end grp handle: 0x0036 uuid: 3a340720-c572-11e5-86c5-0002a5d5c51b
>attr handle: 0x0037, end grp handle: 0xffff uuid: 00001530-1212-efde-1523-785feabcd123

What further information do you need, to investigate this issue?

Cheers,
MA

**Comment by aicherm** [comment]
Solved by completely deleting the device from bluez, reset and do re-paring only with tuhi.

**Comment by whot** [comment]
ftr, `e6` is the initial connection attempt and it provides the uuid as authentication factor. If that doesn't match what the device has stored, you get the auth error. This can happen when you use the device with a different tool (e.g. Inkspace) or when you modify/lose/reset the tuhi config. In all of these cases, re-registering the device with tuhi is sufficient but I'm slightly worried that tuhi didn't prompt you to do this.
