### ISSUE TITLE
Create a path instead of a group of lines

### ISSUE THREAD

**Issue by nico202** [tuhiproject/tuhi#213]
Hi, first of all thanks for this! I bought a bamboo slate a4 today and your program is working great :)

I never used their program, and I'm not an svg expert, but I noted that the exported svg is gigantic (1Mb for a simple image). So I opened it in inkscape, and realized that paths are not paths, but a group of line objects. A free-hand line in inkscape is instead exported as a path (whose representation is smaller). This allows also things like "path simplification", currently impossible.

I think that the "correct" way to represent this is to have a path+stroke (https://graphicdesign.stackexchange.com/questions/73311/what-is-the-difference-between-a-path-and-a-stroke)

**Comment by nico202** [comment]
I think [here](https://forum.affinity.serif.com/index.php?/topic/50924-wacom-bamboo-slate-to-affinity-designer-svg-export-issue/) there's some info on the format they use. Anybody has the official program and can share an example svg?

**Comment by whot** [comment]
fwiw, the device itself gives us x, y and pressure, all in device coordinates. We convert this to the 'crazy' svg because I'm not aware of an SVG function that lets us deal with pressure in some other way.  The code itself is quite trivial, it's a grand total of 80 loc: https://github.com/tuhiproject/tuhi/blob/master/tuhi/svg.py

Having said that - without completely dropping pressure I don't know how we could fix this but I'm open for any ideas you have.

**Comment by lukyluket** [comment]
Maybe one could have a look into different format such as xoj files like those of Xjournal. 
I am not sure if they are vectorized but the program is page based as are our slates, 
and support pressure.
The new Xjournalpp also has the possibility to write plugins, maybe one could think of a plugin for importing from tuhi

**Comment by bentiss** [comment]
Regarding the xoj file format: it's gzipped xml, according to http://xournal.sourceforge.net/manual.html#file-format:

> Layers and strokes
> 
> After the line specifying the background, the remainder of a `<page>` section is occupied by one or more layer sections
> ```xml
> <layer> ... </layer>
> ```
> describing the various items within a layer. Every `page` must contain at least one `layer`; a `layer` may be empty. The successive layers are listed in their stacking order, from bottom to top.
> 
> A `layer` consists of a collection of items, listed in the order in which they should be drawn (from bottom-most to top-most). Up to version 0.3.3, the only legal contents within a layer are strokes. The format of a stroke is:
> ```xml
> <stroke tool="..." color="..." width="...">
> ... list of coordinates ...
> </stroke>
> ```
> The `tool` attribute can take the values `"pen"`, `"highlighter"`, or `"eraser"` depending on the tool used to create the stroke (pen, highlighter, or whiteout eraser); a value of `"highlighter"` indicates that the stroke should be painted in a partially transparent manner (Xournal uses an alpha coefficient of 0.5).
> 
> The `color` attribute can take one of the standard values `"black"`, `"blue"`, `"red"`, `"green"`, `"gray"`, `"lightblue"`, `"lightgreen"`, `"magenta"`, `"orange"`, `"yellow"`, `"white"`, or can specify a hexadecimal RGBA value in the format `"#rrggbbaa"`.
> 
> The `width` attribute is a floating-point number (or a sequence of floating-point numbers starting with version 0.4.2), and specifies the width of the stroke in points (1/72 in). (For a variable-width stroke, the `width` attribute contains a whitespace-separated succession of floating-point values: first the nominal brush width, and then the width of each successive segment forming the stroke.)
> 
> The list of coordinates is simply a succession of floating-point values, separated by whitespace. The number of given values must be even; consecutive pairs of values give the x and y coordinates of each point along the stroke. These values are expressed in points (1/72 in). The coordinates (0,0) represent the top-left corner of the page: hence x is measured from the left of the page, and y is measured from the top of the page.
> 
> Every stroke must contain at least two points (four floating point values). Moreover, two consecutive points on the stroke should be spaced no more than 5 units apart or so; longer line segments should be subdivided as appropriate (otherwise the eraser tool will not interact properly with the stroke). The default precision used by Xournal for the x,y coordinates is 0.01 unit (1/7200 in).

So creating such file should be easy, but we would lose the versatility SVG can provide.

Besides that, we had a setting in a config file whether we wanted to use the pressure or not when creating the SVG.

**Comment by whot** [comment]
> So creating such file should be easy, but we would lose the versatility SVG can provide

we already allow exporting to png so it's possible to add a file exporter for something else.

> Besides that, we had a setting in a config file whether we wanted to use the pressure or not when creating the SVG.

I dropped that in the tuhigui conversion, mostly because with a device like this why *wouldn't* you want to use pressure? I'd rather export all we have and let the target tool (inkscape, xournal, whatever) deal with removing it again.

**Comment by whot** [comment]
I think this was fixed in #285
