### ISSUE TITLE
Live Mode Wiki

### ISSUE THREAD

**Issue by aicherm** [tuhiproject/tuhi#214]
I could not get the Live-Mode running. Perhaps someone wants to write a short HowTo use it?
Or maybe it is just not functional with the current build?
I would be really thankful :)

Awesome that this project is so active now!

Cheers!

**Comment by bentiss** [comment]
Done: https://github.com/tuhiproject/tuhi/wiki/Using-Tuhi#advanced-usage-live-mode

Not the best document ever, but, meh, I hope it'll help

**Comment by aicherm** [comment]
Thanks a lot! I had trouble with the include path to tuhi.dbusclient. But works like a charm now!

**Comment by whot** [comment]
Moved it to https://github.com/tuhiproject/tuhi/wiki/Live-Mode
