### ISSUE TITLE
Embedded .ui file is not translatable

### ISSUE THREAD

**Issue by piotrdrag** [tuhiproject/tuhi#216]
tuhi/gui/window.py has embedded XML code to make the main menu, so the menu is not localized.

**Comment by whot** [comment]
~~this is one thing I couldn't figure out through googling: can this xml file be placed elsewhere for easier translation? If not, i'll just switch to a python string format with gettext, that should do the job. But it feels dirty, even dirtier than right now.~~

nevermind, figured it out this time a minute after looking at the code :)
