### ISSUE TITLE
C# Port help

### ISSUE THREAD

**Issue by gabrielfreire** [tuhiproject/tuhi#224]
Hi, lovely work you've done here.

I'm trying to port some bits of your lovely work to C# in order to successfully Pair a Xamarin mobile App with the Wacom Bamboo Slate.

What i currently can do is **List devices** and **Connect to Bamboo Slate**, but i can not properly
finish the *pairing* routine.

I'm listening to the 
- Command Event Characteristic
- Command notify Characteristic

Command Event Characteristic returns `[ 239, 1, 0 ]` as soon as i connect.

i believe that `239` is `opcode` for `User Confirmation in progress` or something like that and `0` seems to be `SUCCESS`.

then i send `Register Press Button Command` and `Register Wait Press Button Command`
Both of them makes **Command notify Characteristic** trigger and return `[0xb3, 0x01, 0x01]`

I'm not sure i understood correctly, but reading your code it seems that `0xb3` is the default `opcode` response that doesn't require overriding your `_handle_reply` method, but `0x01` means `GENERAL_ERROR` and after getting this response, i press the physical button on the Bamboo Slate anyway to see if something happens but **nothing really happens** and the blue light keeps blinking forever until it times out and i get disconnected.

i'm not sure if i'm skipping any step i have to perform before sending the `Press Button`/`Wait Press Button` messages.

Below are the values i have for each `opcode` i'm trying to perform
```csharp
public static int OPCODE_CONNECT = 0xe6;
public static int OPCODE_REGISTER_COMPLETE = 0xe5;
public static int OPCODE_REGISTER_PRESS_BUTTON = 0xe7;
public static int OPCODE_REGISTER_WAIT_FOR_BUTTON = 0x00;
```

These values could also be wrong, 
I hope i explained my situation clearly, could you help me please?  👍  
Thank you

**Comment by whot** [comment]
ftr, "pairing" has a specific meaning in bluetooth so we use the term "registering" instead to avoid confusion.

`0xb3` is the generic handler, where `0x00` is success and anything else is an error. but not all requests use that one, some of the registering process has custom replies. grep for `RegisterHelper` in tuhi, that's the class we use to register a new device. The two messages are `REGISTER_PRESS_BUTTON` and then `REGISTER_WAIT_FOR_BUTTON`, both listed [here](https://github.com/tuhiproject/tuhi/blob/master/tuhi/protocol.py).

as for the `239` value - that's `0xef` but we don't seem to have code for that. So I'm not sure where this comes from.

That's about all I can say for now, it's hard to debug this remotely as I don't know what your application is doing. And to have any idea what's going on I'd have to see the message exchange between the tablet and your device, but even then it could be down to some timing issue or something similar, so either way it's likely going to come down to you trying to figure out where your command stream differs from the one Tuhi sends to the device.

**Comment by gabrielfreire** [comment]
Thank you @whot , i will keep trying.

I gave some reading about bluetooth and some documentation about bamboo slate, and it seems that the device can only register to one application at a time, i currently have the **inkspace app** with the device paired on my phone, i haven't thought about that but it could be the issue, i will remove the device and the app and test again tomorrow.

Yes, i got the information about how to register from `WacomRegisterHelper` class.

Would you mind pointing me to the direction where i can learn how to figure these things out ? how did you guys figure the details about these devices ? do you watch the the communication and take notes of what's happening ? how do you do that ? i'm new to this bluetooth thing and would appreciate some light on how to figure the meaning for so many bytes. Is there a software that i can install to watch these bytes communicating ?

Thanks again.

**Comment by whot** [comment]
the registration works in assigning a random UUID to the device and then using that as authentication. that can be overwritten during the registration process so it doesn't matter if you have that tablet already registered with inkspace since you'll just give it a new UUID. It does mean that you can't use both without having to re-register every time (annoying but not destructive).

If you snoop the UUID that inkspace uses, you don't even need to re-pair, you can just hardcode that one.

As for how to figure this out: if you have inkspace installed on an android tablet and you set the android tablet into developer mode, you can record bluetooth interactions. Then you download the `btsnoop_hci.log` file and stare long and hard at it until it all makes sense. Or, if you want to be boring you just use the [parse_log.py](https://github.com/tuhiproject/tuhi/blob/master/tools/parse_log.py) script from tuhi ;)

**Comment by gabrielfreire** [comment]
Ahhhh so that's probably what my issue is i think. I am not generating random UUID, i am using the Device ID which is all wrong and would never work, so i need to create an UUID myself, right ? haha, well, i got it all wrong, my bad. i will definitely try that.

Also, i found the **inkspace app** decompiled on github

[removed]

thank you for your help

**Comment by whot** [comment]
had to remove the link and the code copied. decompiling is legally iffy at best and outright illegal in some jurisdictions. Please don't post links to the decompiled source in the future (at least not without verifying whether it can be posted first).

**Comment by gabrielfreire** [comment]
ah ok, sorry i didn't know that, just wanted to help, by the way i managed to pair by generating a random UUID myself, thank you

**Comment by whot** [comment]
yeah, no worries, I understand :)

**Comment by whot** [comment]
I think the original question here is answered, let's close this
