### ISSUE TITLE
Installing on Ubuntu 18.04 files are not written on the disk

### ISSUE THREAD

**Issue by lukyluket** [tuhiproject/tuhi#230]
The main problem I am facing is that the files are not written on the disk.
They look like they are saved in the dialog opened when I press the download icon. 

However I am unable  to located them from the terminal or any other application neither in the folder I chose, nor anywhere else.

I summarize the installation steps I followed, in order to give a clue

I just post the step I needed to install tuhi. 
First of all the meson way, does not work for me. The distro meson is obsolete.
I tried to install it through 
pip3 install meson but then pygobject couldn't be installed due to pycairo. I have googled the forum but after one hour haven't been able to proceed.

So I decided to give a try with flatpack.
There there are some few steps that I list here
1) flatpak --user install org.gnome.Sdk/x86_64/3.32
2)  flatpak --user install org.gnome.Platform/x86_64/3.32

(in the flatpak page 3,30 is listed)

Then everything went smooth but a very long waiting for the window to appear after having launched from the terminal, and no possibility to save the files to the disk as mentioned above.

**Comment by whot** [comment]
see the [wiki](https://github.com/tuhiproject/tuhi/wiki/Log-files) for the flatpak location for the various log files. The weird thing is: the file dialog merely copies an svg file that already sits on disk, just into the directory you specified. Of all the things in Tuhi, that's the last thing that should go wrong.

I've updated the [installation page](https://github.com/tuhiproject/tuhi/wiki/Installation) now too, thanks. Though at least for the extra steps: flatpak pulls that down automatically, maybe Ubuntu has an old or buggy version of that?

**Comment by lukyluket** [comment]
First thing I notice from the wiki that my $XDG_DATA_DIR is not set, 
I found however the data in the directory
$HOME/.var/app/org.freedesktop.Tuhi
[tuhi-19-11-12-22:39:33.log](https://github.com/tuhiproject/tuhi/files/3840299/tuhi-19-11-12-22.39.33.log)

and I attach here one of the log file, 
can you see anything strange. 

All the json files are there, but they do not get converted to svg

**Comment by lukyluket** [comment]
Just an update, I noticed that  from the file browser window every folder including my home directory seems empty.  It is pretty weird

![Screenshot from 2019-11-13 10-31-36](https://user-images.githubusercontent.com/7592331/68750826-cdc18580-0600-11ea-9f81-37093ec07b80.png)

**Comment by whot** [comment]
the save dialog defaults to show "*.svg" files only, so it won't show other files in the same directory. 
But what about that 'untitled.svg', isn't that your drawing? The temporary SVGs are in `$XDG_CACHE_HOME/tuhi` but I don't know off-hand what the flatpak value for that is.

**Comment by lukyluket** [comment]
once more echo $XDG_CACHE_HOME is empty, as for the above screenshot, 
nothing changes, still no files read from the filesystem.

 By running flatpak with -vv option 
I obtain  flatpak -vv run org.freedesktop.Tuhi

F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/luca/.local/share/flatpak
F: Opening user flatpak installation at path /home/luca/.local/share/flatpak
F: Opening user flatpak installation at path /home/luca/.local/share/flatpak
F: Cleaning up unused container id 515659064
F: Allocated instance id 1787058585
F: Add defaults in dir /org/freedesktop/Tuhi/

F: Add locks in dir /org/freedesktop/Tuhi/
F: Disallowing network access
F: Allowing wayland access
F: Allowing x11 access

Also by setting by hand both $XDG_CACHE_HOME and $XDG_DATA_HOME a directory structure is created but left completely empty

**Comment by lukyluket** [comment]
I think I have solved it. Not sure why it is supposed to work like this but I found this post [https://github.com/flatpak/flatpak/issues/2185](https://github.com/flatpak/flatpak/issues/2185) where they suggest that one can give or not access to the filesystem to flatpak.

Now I wrote
flatpak --user override --filesystem=home   org.freedesktop.Tuhi

on the terminal and everything work. 

A side remark, I do not like flatpak. It seems very unrensponsive and for installing tuhi it downloaded more than an extra Gigabyte of stuff on a working Linux Distro. 

Maybe we should manage to make the python version installable on Ubuntu 18.04

Cheers

**Comment by whot** [comment]
> A side remark, I do not like flatpak. It seems very unrensponsive and for installing tuhi it downloaded more than an extra Gigabyte of stuff on a working Linux Distro.

flatpak's dependencies are like shared libraries. the first one downloads a lot, the second one re-uses what's already there. if you only ever use one flatpak it's not efficient but that is true for any shared library system. And the whole point of flatpak is that it *doesnt* use the shared libraries on the distribution - because those may be the wrong version as you discovered with pygobject/pycairo/etc.

but anyway, verified, something is broken with the file saving under flatpak. It seems to save it but not where it's supposed to...
