### ISSUE TITLE
Points as time series data

### ISSUE THREAD

**Issue by JohnRouter** [tuhiproject/tuhi#231]
Is there a way to export the points with their corresponding timestamp?
Is it possible to gather other pen parameters like pen_z, pen_x_tilt, pen_y_tilt, pen_rotation?

**Comment by whot** [comment]
we only get x/y and pressure from the device, the rest doesn't exist. as for the rest, the raw data is exported as yaml file into the logs at `$HOME/.local/share/tuhi/<bluetooth addr>/` and you can process those. Look at [`tools/raw-log-converter.py`](https://github.com/tuhiproject/tuhi/blob/master/tools/raw-log-converter.py) in the source tree for inspiration.

**Comment by JohnRouter** [comment]
The raw-log-converter.py would not help because the time component for each point (x, y and pressure) is never stored. There is only 1 timestamp at the very beginning of the .yaml file and what I am trying to get is 1 timestamp per point. 
e.g if I have 1000 points with their corresponding x/y/pressure I would like to have also 1000 timestamps.

**Comment by bentiss** [comment]
> There is only 1 timestamp at the very beginning of the .yaml file and what I am trying to get is 1 timestamp per point.

I don't think we have access to that information from the data we receive. We do have a global timestamp, and then a series of points, but AFAICT, there is no timestamp in the middle.

I *think* the points are regularly given, (i.e. every ms, 2ms, or 8ms, can't know). But the device doesn't gives us more than the `raw` logs, and so if the information is not there, it's not possible to get back to it.

**Comment by whot** [comment]
I think on the newest devices (intuos pro) there's a timestamp per stroke but definitely not per point.

**Comment by JohnRouter** [comment]
Thank you for the info!

**Comment by whot** [comment]
checked the code, look at `protocol.py:StrokeHeader`. We have timestamps per stroke but don't use those, see the `StrokeFile` class, so they effectively get discarded.

Should be easy-enough to bubble this up so it at least shows up in the json files, start with the `namedtuple` in `StrokeFile._parse_data()` and work your way up from there.

**Comment by JohnRouter** [comment]
> I think the points are regularly given, (i.e. every ms, 2ms, or 8ms, can't know). But the device doesn't gives us more than the raw logs, and so if the information is not there, it's not possible to get back to it.

I just checked out the sampling rate: it is 5 ms. That means that using the stroke initial timestamp and adding the delta time, every point can be described also in the time dimension. Thank you guys for your help!

**Comment by whot** [comment]
sure, glad you found what you needed.

**Comment by JohnRouter** [comment]
Just one more thing:  is it possible to retrieve the timestamp from `protocol.py:StrokeHeader._parse_intuos_pro()` in ms?

**Comment by whot** [comment]
you generally don't want to deal with the functions directly but let the class do its thing and then access the field itself. so in that case, the `stroke_header.timestamp` attribute and that should always be in millis. You don't need to care which device is underneath.

**Comment by JohnRouter** [comment]
Sorry to bother you again. I might not be getting this right, but both `StrokeHeader.timestamp` and `StrokeFileHeader.timestamp` attributes are in sec. and not millisec. 
For `StrokeFileHeader.timestamp` only 4 bytes are used and millisec are always zero:

```
self.timestamp = int.from_bytes(data[4:8], byteorder='little')
#plus two bytes for ms, always zero
```
And for `StrokeHeader.timestamp` also only 4 bytes are used:

`self.timestamp = int.from_bytes(payload[2:6], byteorder='little')`

What does ` # FIXME: plus two bytes for milis` in line 1743 refer to? Which two bytes?
Thank you in advance!

**Comment by whot** [comment]
hmm, trying to page this info back into my brain... so first - you're right, timestamps are in seconds but we could do the python thing and make them floats to include the millis. This will require a bit of rework to make sure we don't expose those as filenames (because we use the timestamps as filenames and in logs etc.).

IIRC the FIXME refers to the last two bytes being milliseconds but I didn't bother with them. There's a chance they're 0 anyway but I don't have the setup ready to immediately test, sorry. Those two bytes are supposed to be 100s of microseconds (0.1 ms) according to the spec.
