### ISSUE TITLE
meson warning

### ISSUE THREAD

**Issue by jose1711** [tuhiproject/tuhi#233]
this can be fixed easily:
```
WARNING: Project specifies a minimum meson_version '>= 0.50.0' but uses features which were added in newer versions:
 * 0.51.0: {'modules arg in python.find_installation'}
```

**Comment by whot** [comment]
this is a false positive, meson is a bit too simplistic here in how it checks work. See [the code here](https://github.com/tuhiproject/tuhi/blob/master/meson.build#L41), the bit in question is actually behind a meson version check. Thanks though!
