### ISSUE TITLE
Add support for Augmented Paper

### ISSUE THREAD

**Issue by niclashoyer** [tuhiproject/tuhi#237]
I pushed a number of PRs to support [Augmented Paper](https://www.montblanc.com/de-de/landingpages/augmented-paper.html) (old version) which is technically a Spark device with a different company ID and name.

 - #236 adds support for device names longer than one request (in this case `Montblanc Augmented Paper`), this needs to be checked against vanilla Spark
 - #235 adds the company ID
 - #234 workaround for #229, which I also hit while testing

Support for the new version "Augmented Paper +" may be possible, because it may be a rebranded Intuos Pro, but this is not part of the PRs, as I can't test that.

**Comment by niclashoyer** [comment]
One other thing I noticed: as the Augmented Paper has the button on the right side, everything seems to be flipped, so my notes are upside down in tuhi. Is there a setting to change this? Not a big problem, because one can rotate them manually.

**Comment by whot** [comment]
there's no setting, I'd say it'd be more sensible to add this as a fixed thing for that device so it comes out pre-rotated already.

**Comment by whot** [comment]
AIUI this is basically fixed now, all the above MRs are merged. Happy to take a pull request to change the device rotation.
