### ISSUE TITLE
any chance for a windows port?

### ISSUE THREAD

**Issue by aleqx** [tuhiproject/tuhi#242]
Lovely work! Thank you so much for the time and effort you devoted to this. The fact that Wacom forces users to register and use their cloud in order to be able to export to SVG etc makes Wacom a nono company for me -- I only found out after I bought their Bamboo Slate and I'm looking for alternative products in A4 size (do you know any, btw?)

My question was - any chance for a windows port, or how much hassle would it be to get Tuhi to work on windows? Spinning up a linux VM just for this is overkill but may be less hassle overall.

**Comment by bentiss** [comment]
Sorry, we depend on bluez and dbus to access the device, and I don't think you can run this on Windows.
[after a check, yes, bluez is a Linux only project]

So nope, we can't do that, it would require to rewrite everything with a new toolkit.

**Comment by jiucenglou** [comment]
> Spinning up a linux VM just for this is overkill but may be less hassle overall.

Could you share your opinions what is the working way to use Tuhi on Windows ?
