### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by karlkappe** [tuhiproject/tuhi#252]
Hello 
I tried to build tuhi from source on a freshly installed Ubuntu 20.4
This is the log-file. I have no idea what to do now
Build started at 2020-04-22T10:52:55.237332
Main binary: /usr/bin/python3
Build Options: 
Python system: Linux
The Meson build system
Version: 0.53.2
Source dir: /home/user/tuhi
Build dir: /home/user/tuhi/builddir
Build type: native build
Project name: tuhi
Project version: 0.3
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Pkg-config binary for MachineChoice.HOST is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default pkg-config fallback at pkg-config
Trying pkg-config binary pkg-config for machine MachineChoice.HOST at ['/usr/bin/pkg-config']
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'pygobject-3.0' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion pygobject-3.0` -> 0
3.36.0
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --cflags pygobject-3.0` -> 0
-I/usr/include/pygobject-3.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config pygobject-3.0 --libs` -> 0
-L/usr/lib/x86_64-linux-gnu -lgobject-2.0 -lglib-2.0
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config pygobject-3.0 --libs` -> 0
-lgobject-2.0 -lglib-2.0
Run-time dependency pygobject-3.0 found: YES 3.36.0
WARNING: Gettext not found, all translation targets will be ignored.
Configuring AboutDialog.ui using configuration
Configuring org.freedesktop.Tuhi.appdata.xml.in using configuration
Pkg-config binary for MachineChoice.BUILD is not cached.
Pkg-config binary missing from cross or native file, or env var undefined.
Trying a default pkg-config fallback at pkg-config
Trying pkg-config binary pkg-config for machine MachineChoice.BUILD at ['/usr/bin/pkg-config']
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Determining dependency 'glib-2.0' with pkg-config executable '/usr/bin/pkg-config'
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --modversion glib-2.0` -> 0
2.64.2
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config --cflags glib-2.0` -> 0
-I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-L/usr/lib/x86_64-linux-gnu -lglib-2.0
PKG_CONFIG_PATH: 
Called `/usr/bin/pkg-config glib-2.0 --libs` -> 0
-lglib-2.0
WARNING: Project targeting '>= 0.50.0' but tried to use feature introduced in '0.51.0': modules arg in python.find_installation
Program python3 (svgwrite, xdg, gi, cairo) found: YES (/usr/bin/python3) modules: svgwrite, xdg, gi, cairo
Configuring tuhi using configuration
Configuring tuhi.devel using configuration
Configuring tuhi-gui using configuration
Configuring tuhi-gui.devel using configuration
Program meson_install.sh found: YES (/usr/bin/env sh /home/user/tuhi/meson_install.sh)

meson.build:115:0: ERROR: Tried to assign an invalid value to variable.

**Comment by whot** [comment]
> WARNING: Gettext not found, all translation targets will be ignored.

That's the key error message here, the rest is [this meson bug](https://github.com/mesonbuild/meson/issues/6165)
