### ISSUE TITLE
Does `live-mode` support Bamboo Spark?

### ISSUE THREAD

**Issue by Pavlos1** [tuhiproject/tuhi#254]
Hello,

Firstly: many thanks for your work making the use of these devices with Linux possible.

I have a Bamboo Spark that is registered to `tuhi` and can successfully synchronize drawings.

However, when running `tuhi-live.py` it creates the input device (visible to `xinput`), but doesn't seem to send any inputs. (And `evemu-record ` does not pick anything up when I draw on it.)

Is there some additional setup I need to do, or is live mode not supported on the Spark? (My machine runs i3wm, if that is relevant.)

**Comment by Pavlos1** [comment]
Update: I got it to move the mouse around by having a drawing pending before clicking the button.

But the device seems to "get bored" after a couple of seconds and disconnects from bluetooth.

**Comment by bentiss** [comment]
I don't think we implemented the live protocol for the spark. Sorry
