### ISSUE TITLE
Python import fail on ubuntu 18.04

### ISSUE THREAD

**Issue by HoBoIs** [tuhiproject/tuhi#258]
tuhi.devel works fine but the files in /usr/local/libexec/tuhi (tuhi-gui  and tuhi-server) not in the tuhi library (created next to builddir when installed) so they can't import like 'import tuhi.base' it should be import TUHIPATH.tuhi.base also some files in builddir (tuhi and tuhi-server as I saw) import like that so that should be changed too. (or adding TUHIPATH to pythons searchpath on install)
ps.:
if you put
import sys
sys.path.append("/path/to/thui") 
to the begining of each file i mentiond it works fine

**Comment by whot** [comment]
There shouldn't be anything special about how tuhi loads the files. If you're not installing in the expected location (`/usr/libexec` I think) then you need to adjust your `PYTHONPATH` accordingly. IOW, I think this is a problem between where your system installed the files vs where your system python installation expected packages to be installed.
