### ISSUE TITLE
Project specifies a minimum meson_version '>= 0.50.0' but uses feature of 0.51.0

### ISSUE THREAD

**Issue by ericzolf** [tuhiproject/tuhi#259]
During `meson build` the following error message appears:

```
WARNING: Project specifies a minimum meson_version '>= 0.50.0' but uses features which were added in newer versions:
 * 0.51.0: {'modules arg in python.find_installation'}
```

And indeed `meson.build` contains the line `meson_version: '>= 0.50.0')` which apparently should be increased (I didn't get any issue as I had meson 0.55 installed).

**Comment by whot** [comment]
this one is a (rather annoying) false positive. The call in question is actually behind a check for meson >= 51 but meson *still* complains about it. We have a fallback for 0.50 so the file should work on either version. I think meson has a bug open about this but I couldn't immediately find it. Thanks though :)
