### ISSUE TITLE
Updated but does not wrk anymore

### ISSUE THREAD

**Issue by lukyluket** [tuhiproject/tuhi#267]
Hello there, I have updated the tuhi installation, 
Have tried both directly and with flatpack 

In both cases  I get the following outcome after installation 

_Traceback (most recent call last):
  File "/usr/local/libexec/tuhi/tuhi-gui", line 31, in <module>
    from tuhi.gui.application import main
ModuleNotFoundError: No module named 'tuhi.gui'

and nothing happens. 

Am I doing something wrong?

Thank you 
Luca

**Comment by whot** [comment]
seems to be an installation issue or a python path issue, tuhi should install `$prefix/lib/python3.8/site-packages/tuhi/gui/` which is the module that `tuhi-gui` is trying to load. either it didn't get installed for some reason or your python path doesn't point to that, try `python3 -c 'import sys; print(sys.path);'` to check what's in the path (e.g. Fedora's default path does **not** include `/usr/local`) so you have to manually set `$PYTHONPATH`.

**Comment by lukyluket** [comment]
Thanks Peter, I checked a couple of things, 
I do have the module in /usr/local/lib/python3.6/site-packages/tuhi/gui

This is the outcome of the installation, 
ninja: Entering directory `builddir'
[5/6] Installing files.
Installing subdir /home/luca/tuhi/tuhi to /usr/local/lib/python3.6/site-packages/tuhi
Installation failed due to insufficient permissions.
Attempting to use polkit to gain elevated privileges...
Installing subdir /home/luca/tuhi/tuhi to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/drawing.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/dbusserver.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/wacom.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/util.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/base.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/ble.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/uhid.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/export.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/config.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/__init__.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/protocol.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/dbusclient.py to /usr/local/lib/python3.6/site-packages/tuhi
Installing /home/luca/tuhi/tuhi/gui/drawing.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/luca/tuhi/tuhi/gui/drawingperspective.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/luca/tuhi/tuhi/gui/application.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/luca/tuhi/tuhi/gui/config.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/luca/tuhi/tuhi/gui/README.md to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/luca/tuhi/tuhi/gui/__init__.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing /home/luca/tuhi/tuhi/gui/window.py to /usr/local/lib/python3.6/site-packages/tuhi/gui
Installing data/org.freedesktop.Tuhi.desktop to /usr/local/share/applications
Installing data/org.freedesktop.Tuhi.appdata.xml to /usr/local/share/metainfo
Installing data/tuhi.gresource to /usr/local/share/tuhi
Installing org.freedesktop.Tuhi.desktop to /usr/local/share/applications
Installing org.freedesktop.Tuhi.appdata.xml to /usr/local/share/metainfo
Installing /home/luca/tuhi/data/org.freedesktop.Tuhi.svg to /usr/local/share/icons/hicolor/scalable/apps
Installing /home/luca/tuhi/data/org.freedesktop.Tuhi-symbolic.svg to /usr/local/share/icons/hicolor/symbolic/apps
Installing /home/luca/tuhi/builddir/tuhi to /usr/local/bin
Installing /home/luca/tuhi/builddir/tuhi-gui to /usr/local/libexec/tuhi
Installing /home/luca/tuhi/builddir/tuhi-server to /usr/local/libexec/tuhi
Installing /home/luca/tuhi/data/org.freedesktop.Tuhi.svg to /usr/local/share/icons/hicolor
Running custom install script '/home/luca/.local/bin/meson --internal gettext install --subdir=po --localedir=share/locale --pkgname=tuhi'
Installing /home/luca/tuhi/builddir/po/it.gmo to /usr/local/share/locale/it/LC_MESSAGES/tuhi.mo
Installing /home/luca/tuhi/builddir/po/pl.gmo to /usr/local/share/locale/pl/LC_MESSAGES/tuhi.mo
Running custom install script '/usr/bin/env sh /home/luca/tuhi/meson_install.sh'
gtk-update-icon-cache: Cache file created successfully.


Now I set the path variable manually as you can see from 
python3 -c 'import sys; print(sys.path);'
['', '/usr/local/lib/python3.6/site-packages/tuhi/gui', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/home/luca/.local/lib/python3.6/site-packages', '/usr/local/lib/python3.6/dist-packages', '/usr/local/lib/python3.6/dist-packages/tuhi-0.1-py3.6.egg', '/usr/local/lib/python3.6/dist-packages/svgwrite-1.2.1-py3.6.egg', '/usr/local/lib/python3.6/dist-packages/pyxdg-0.26-py3.6.egg', '/usr/local/lib/python3.6/dist-packages/pyparsing-2.3.1-py3.6.egg', '/usr/lib/python3/dist-packages']

However I still get the same error 
Traceback (most recent call last):
  File "/usr/local/libexec/tuhi/tuhi-gui", line 31, in <module>
    from tuhi.gui.application import main
ModuleNotFoundError: No module named 'tuhi.gui'

Thanks for the help, 

Luca

**Comment by whot** [comment]
> Now I set the path variable manually as you can see from
``` python3 -c 'import sys; print(sys.path);'
['', '/usr/local/lib/python3.6/site-packages/tuhi/gui', ...
```

Change this to `'/usr/local/lib/python3.6/site-packages/'`, that's the python module path, `tuhi/gui` is the actual module (package) then.

**Comment by lukyluket** [comment]
Done! it works, thanks
Luca
