### ISSUE TITLE
Can't build in Ubuntu 20.04 or 20.10: "Tried to assign an invalid value to variable."

### ISSUE THREAD

**Issue by jtv** [tuhiproject/tuhi#270]
I'm running into trouble building, using both Ubuntu 20.04 and Ubuntu 20.10.

I _think_ I've got the dependencies installed, with a bit of trial and error.  But meson fails on the first call to `i18n.merge_file`:

    meson.build:115:0: ERROR: Tried to assign an invalid value to variable.

Luckily the variable (`desktop_file`) was only used in one place, which I could comment out.  But then it broke at the _other_ call to `i18n.merge_file`:

    meson.build:115:0: ERROR: Tried to assign an invalid value to variable.

**Comment by whot** [comment]
This is a meson error, see https://github.com/mesonbuild/meson/issues/6165, installing `gettext` should fix it.
