### ISSUE TITLE
translation: added turkish language

### ISSUE THREAD

**Issue by gunduzhan** [tuhiproject/tuhi#274]
Hi,
Like your app and congrats your efforts. Successfuly tested and used with Intuos Pro Paper. I really liked!
And also here's Turkish translation.

Good luck!

[tr.zip](https://github.com/tuhiproject/tuhi/files/5909979/tr.zip)

**Comment by whot** [comment]
Thanks for the translation! Please file this one as pull request so we can run the CI on it and it has the proper attributions, etc.

**Comment by whot** [comment]
Nevermind, you already did this in #275, oops :smile:
