### ISSUE TITLE
Extracting UUID from Wacom Inkspace

### ISSUE THREAD

**Issue by vasvir** [tuhiproject/tuhi#278]
Hi I saw the FAQ here: https://github.com/tuhiproject/tuhi/wiki/FAQs#can-i-use-both-wacom-inkspace-and-tuhi

I build a little script that it can extract the UUID from inkspace here:  https://github.com/vasvir/wacom-inkspace-appid-extractor

I found no mailing list and I wasn't able to submit a pull request for the wiki in an easy way hence the mini project as a potential answer to the particular FAQ.

Thanks for the tuhi project.

**Comment by whot** [comment]
Thanks! I've linked to this issue here in the FAQ now, which allows users to follow through to the project.
