### ISSUE TITLE
Pulling pen data from Bamboo Folio using tuhi

### ISSUE THREAD

**Issue by chughes113** [tuhiproject/tuhi#280]
Hi everyone,

Apologies if this is the wrong place to go, so please direct me elsewhere if that's the case!

My goal is to grab real-time pen data from from my Bamboo Folio. I believe I've successfully connected the Bamboo Folio to my rpi using tuhi-live, but I suppose I have a stupidly fundamental question: after the connection is established (see below), I'm not sure what comes next in order to grab pen data - should the data be already displaying in the prompt as I write on the Folio?  Are there commands I should be using to enable this?

I know this wasn't tested on the Bamboo Folio, so it's a bit difficult for me to know whether I'm seeing what I should be seeing or whether I'm just dumb :)

(```INFO: Connected to the Tuhi daemon```
```INFO: starting live on XX:XX:XX:XX:XX:XX - Charlie's Bamboo Folio, please press button on the device```
```23:49:54 INFO: tuhi.wacom: dimensions: 29700x21600, point size 10µm```)

Thanks for all your help both in developing tuhi, but also in creating a forum to ask questions,

Charlie

**Comment by whot** [comment]
In theory, once the tablet is connected a uhid device should be created that takes the input from the bamboo and forwards it through a kernel evdev node - which userspace will pick up like any other device. Do you see any new device nodes being created? Is the above the whole log?

**Comment by whot** [comment]
a year of crickets, let's close this
