### ISSUE TITLE
SVG Export with paths instead of lines

### ISSUE THREAD

**Issue by doctormo** [tuhiproject/tuhi#284]
- Inkscape programmer here.

The SVG export from tuhi is currently making a lot of very small line segments, which creates very large svg files and will very quickly cause inkscape some serious issues for complex drawings.

Instead of `<g><line>...</g>` elements, it should make `<path d="M x,y x,y x,y...">` paths for each of the pen-on constructs. It's reasonable to split out each of the paths for each pen stroke though, most people wouldn't expect multi-subpath results.

I believe the code is in `tuhi/export.py` lines 93 to 105. This should make a path object instead of a group. I do't know how comprehensive svgwrite is compared to inkscape's own inkex module for path creation, hopefully it has a similar `elem.path.add_line or something similar.

**Comment by rolandixor** [comment]
Pitching in as an artist here, I'd much prefer the above functionality over multiple individual lines.

**Comment by doctormo** [comment]
I've created a best guess for the code above, there was no testing json files or testing framework to run, so i can't be sure it works. But it should be something very much like that.
