### ISSUE TITLE
Make a release

### ISSUE THREAD

**Issue by doctormo** [tuhiproject/tuhi#289]
This is a request to make a release. I'm not sure what the release schedule is, so my apologies if this steps on any of that planning. Just looking at the recent commits looks like tuhi is holding onto changes that could make a 0.6 tag.

**Comment by whot** [comment]
Done! https://github.com/tuhiproject/tuhi/releases/tag/0.6

In case this wasn't bleedingly obvious - we don't have a lot of time for tuhi maintenance right now...

**Comment by doctormo** [comment]
I quite understand and thank you, I owe you one.
