### ISSUE TITLE
Allow for configurable storage destination

### ISSUE THREAD

**Issue by whot** [tuhiproject/tuhi#30]
Right now we're using `$XDG_DATA_HOME`, should probably be configurable.

Which also means we need a tuhi general config in `$XDG_CONFIG_HOME`

**Comment by bentiss** [comment]
I do not think this is a good idea. Persistent storage is intended for internal use, and we want clients to retrieve the data through the DBus API.

Allowing configurable storage would encourage users to use this as a source of data, and we will be stuck with the current file format. We won't be able to compress the files or extend the data by adding internal data in the files.
