### ISSUE TITLE
Flatpak support

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#31]
It would be cool, isn't it?

There is not much that would prevent such a support, so if anyone wants to pick it up...

Bonus point, this will allow to run tuhi on distribution with Python3 older than 3.6

**Comment by hadess** [comment]
You should just need to compile the Python version you need and pygobject inside your Flatpak to overcome this problem. And you could drop it once you have a newer runtime to depend on.

**Comment by bentiss** [comment]
I have actually started working on this (see my [branch wip/flatpak](/bentiss/tuhi/tree/wip/flatpak)).
However, that means the resulting fltapak will have 2 pythons and its libs, and in the end, -ENOTIME.

If you want to pick up from where I was, feel free to do so :)

**Comment by hadess** [comment]
> If you want to pick up from where I was, feel free to do so :)

Unlikely, I don't have the hardware.

**Comment by bentiss** [comment]
> Unlikely, I don't have the hardware.

Heh, no worries.
I wanted to give an other try, and I managed to get the app in the flatpak (see the branch I mentioned above). However, as expected, the bus is not available. What would it take to make a bluez portal (or use the existing one)?

**Comment by hadess** [comment]
You want the `--system-talk-name=NAME` finish-args. It should be enough to allow talking to bluetoothd directly. Ideally, we would be able to separately allow/disallow applications talking to Bluetooth, I don't think there's a need for a portal here.

**Comment by bentiss** [comment]
Thanks a lot! It works.
I need to run with `--own-name=org.freedesktop.tuhi1 --system-talk-name=org.bluez` and that's it ;)

@whot now comes the question whether to bundle/install kete with tuhi

**Comment by bentiss** [comment]
@hadess, an other question please:
our daemon stores some config files in `xdg_data_home`. I have seen that flatpak allows to share part of the filesystem, and more especially `xdg-desktop`. Should I allow such sharing? The app works fine without it so I wonder what is the recommended practice for that.

**Comment by hadess** [comment]
> I need to run with --own-name=org.freedesktop.tuhi1 --system-talk-name=org.bluez and that's it ;)

If you add it to the finish-args in the flatpak-builder json file, you won't need to add that by hand.

Don't poke more holes in the sandbox if you don't need to. If you want to be able to export your data, just make sure to use `GtkFileChooserNative` which will automatically use Portals if inside the sandbox.

**Comment by bentiss** [comment]
> If you add it to the finish-args in the flatpak-builder json file, you won't need to add that by hand.

Yep, thanks, I realized it after a little bit of searching.

> Don't poke more holes in the sandbox if you don't need to. If you want to be able to export your data, just make sure to use GtkFileChooserNative which will automatically use Portals if inside the sandbox.

OK. We do not export data outside of the protocol, so that limits the amount of data we need to access.

I think I am ready to send out the PR now. Thanks for all your help
