### ISSUE TITLE
Only keep 10 drawings at a time (at startup)

### ISSUE THREAD

**Issue by whot** [tuhiproject/tuhi#45]
We don't need more than that for testing and this way we can make sure that no-one is abusing tuhi's storage as permanent storage. Since we may download a number of drawings at once, this check should only be performed on startup on the initial config read.

**Comment by bentiss** [comment]
Now comes the question of which drawings are we going to keep :)
The ones with the most events, the latest ones, or 10 randomly out of all of them?

**Comment by whot** [comment]
The latest ones. otherwise we're likely to confuse ourselves while testing :)
