### ISSUE TITLE
Support Intuos Pro Paper Edition

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#56]
See the title. Difference found so far to Spark/Slate:

- [ ] WACOM_COMPANY_ID is 0x4157
- [ ] register connection is 0x53
- [ ] timestamps are in epoch, not strftime
- [ ] fw version is in raw ascii values
- [ ] set_name doesn't need a terminating linebreak

**Comment by bentiss** [comment]
According to @whot, the protocol is slightly different. We are looking into it

**Comment by bentiss** [comment]
Regarding the `set_name` function, does the Wacom inkspace app append the terminating `\n`? If it does, do we really need to have a special case for the Intuos Pro?

**Comment by whot** [comment]
it doesn't. i only found out about the `\n` when the intuos code didn't work properly on the spark

**Comment by bentiss** [comment]
merged as of #77
