### ISSUE TITLE
Support the Bamboo Folio Smartpad

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#57]
See the title.
It should be working, but we need someone to tell us.

**Comment by silpol** [comment]
how one can try, provided it is available?

**Comment by bentiss** [comment]
If you own a Folio Smartpad, and if your current distribution has python 3.6 natively, it shouldn't be more of just testing if everything works out of the box already:
- run `tuhi.py --verbose`
- in a separate terminal run `./tools/kete.py`
- in kete, start the command `search on`
- press 6 seconds on the folio button
- kete should show you the device in register mode
- in kete: `register XX:XX:...` (replace with the correct device address)
- in kete: `search off` (if the registering process went smoothly)
- then in kete: `listen XX:XX:... `
- draw something on the tablet
- press the button
- kete should show a new drawing
- you can fetch it in kete: `fetch XX:XX:... all`

If anything fails, we will need the logs from the first terminal (the tuhi.py). If all works fine, then congrats :)

**Comment by muesli** [comment]
I can confirm this is working as expected with a Bamboo Folio.

**Comment by whot** [comment]
Hooray! Thanks for testing.
