### ISSUE TITLE
Handle devices with changed UUIDs

### ISSUE THREAD

**Issue by whot** [tuhiproject/tuhi#6]
The UUID on the smartpad is assigned by the host system, so pairing a device, then pairing it with e.g. the Wacom Inkspace app changes the UUID.

Since we have to remember the UUIDs for each device to connect to it, we'll eventually be in the situation where a device known by its Bluetooth MAC address rejects connection because our UUID is wrong and we need to re-pair that device. We need some API to signal this to the client so they can pop up the required notification boxes.

**Comment by bentiss** [comment]
We actually do that now. Sending a PR to notify this from kete.
