### ISSUE TITLE
Install kete?

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#62]
Related to #31 

Kete was initially a debugging client, which explains why it was not part of the setup.py. However, the now shell-like kete makes me think that we might want to rethink whether or not shipping the CLI as part of tuhi.

@whot, any change of mind?

**Comment by whot** [comment]
Very reluctantly tbh. But we should still keep it to the absolute minimum and refuse to add any feel-good feature that goes beyond basic debugging.

**Comment by bentiss** [comment]
One thing I came to realize in trying to include tuhi-kete in the flatpak is that we can simply install it in the flatpak by manually copying in /app/bin. It's not very ideal, but it should allow to provide a test flatpak for people who want to try.

Also, as long as tuhi-kete stays a single file, we can always tell people to do a simple wget to try it.

I think we can close it for now and re-open if needed.

**Comment by whot** [comment]
we should ship it in the flatpak, otherwise it's a bit pointless when you can't talk to it. at least until we have some other UI we can use, because having tuhi sit there without any client is a bit pointless.

**Comment by bentiss** [comment]
The problem with the flatpak, is that it is meant to run only one command by default.
So shipping it in the same flatpak means people have to run:
- `flatpak org.freedesktop.tuhi` for tuhi
- and then `flatpak run --command=/app/bin/tuhi-kete org.freedesktop.tuhi`

That's less than ideal.

OTOH, once the flatpak starts, you can use tuhi-kete outside of the sandbox as it'll talk to tuhi through dbus.

Once thing we might considering, is some kind of autostart of tuhi when we run tuhi-kete from the flatpak.

**Comment by whot** [comment]
Does DBus activation work from within a sandbox somehow? That seems like it's the best option

**Comment by bentiss** [comment]
> Does DBus activation work from within a sandbox somehow? That seems like it's the best option

I might be wrong, but as far as I can tell, DBus activation is done by systemd on the host, so I doubt we can have this in the sandbox. Also, it *seems* to me that DBus action works for system services, not session ones.

Adding a small script to launch tuhi-kete is not a big deal IMO.

Closing for now.
