### ISSUE TITLE
Provide a commandline client

### ISSUE THREAD

**Issue by whot** [tuhiproject/tuhi#7]
Required features:
- [x] list currently known devices
- [x] start listening/stop listening
- [x] connect to a specific device
- [x] list drawings available
- [x] export a drawing to SVG
- [x] ~~delete a drawing~~
- [x] start/stop pairing process
- [x] Pair a specific device by bluetooth address

**Comment by whot** [comment]
a9b6ea68e5 added SVGs, and 7d86305b5242cfcf6 as well for the interactive mode

**Comment by bentiss** [comment]
note: using timestamps is pretty terrible for the clients...

**Comment by whot** [comment]
commandline clients maybe. But in the glorious future where we have a GUI client it just won't matter :)

**Comment by whot** [comment]
On that note, I'm thinking of skipping the "delete a drawing" functionality and replacing it with a count or date-based solution (i.e. limit to 20 drawings max, or delete anything older than 1month).

This would also encourage clients more to not rely on the tuhi daemon for storage...

**Comment by bentiss** [comment]
> On that note, I'm thinking of skipping the "delete a drawing" functionality and replacing it with a count or date-based solution (i.e. limit to 20 drawings max, or delete anything older than 1month).
> This would also encourage clients more to not rely on the tuhi daemon for storage...

Agree to that. A workaround *could* be to ask the clients to mark which ones they want to keep on the next restart of the daemon. But OTOH, it might be just as easier to say "we will just keep the last 20 drawings if the daemon is restarted" (not sure it's interesting to discard the current in-memory drawings)

**Comment by whot** [comment]
Removed the need to have a delete a drawing option, so we're complete in the base functionality we need
