### ISSUE TITLE
Device name handling

### ISSUE THREAD

**Issue by whot** [tuhiproject/tuhi#75]
I haven't actually investigated this but: the bluetooth interface gives us a device name, the 0xbb command gives us a device name. Are these two always the same and if not, which one will we choose to display?

**Comment by bentiss** [comment]
I just made the test. The `0xbb` register is indeed the name. If you select to change the name while pairing on Inkspace, the command is sent with the new name, and this changes both the actual bluetooth name and the result of the `0xbb` command when reading it.

Closing as both values are synched in the firmware
