### ISSUE TITLE
Don't list devices available for registering immediately after start

### ISSUE THREAD

**Issue by whot** [tuhiproject/tuhi#80]
Any device that we currently know about is listed as a device available for registering after search is called. This is incorrect, we should send out the signal once the device starts being actually present and connectable, not just because we've once known about it.

**Comment by bentiss** [comment]
Just for the record, I think we introduced that before being reliable on the RSSI changes (the bluetooth filters while discovering). Because otherwise, we were not sure we would get an RSSI change on the Spark.
