### ISSUE TITLE
live: fix physical dimensions/resolution

### ISSUE THREAD

**Issue by bentiss** [tuhiproject/tuhi#84]
The physical dimensions in the created uhid node are wrong. We need to fix them by inserting them in the report descriptor. I think we can just hard code them in the various `WacomProtocol*` classes

**Comment by whot** [comment]
don't we already have the dimensions (in micron) as the protocol classes' `self.width` and `self.height` anyway?

**Comment by bentiss** [comment]
It's the usual game of not setting proper resolution in the final uhid device. udevadm shows that the device physical size are wrong, and we should just fix them based on our information.

This bug is mainly here to remember that we need to fix those properly (and make sure it's compatible with #88)
